name: Benchmark
on:
  push:
    branches:
      - master
  workflow_dispatch:
permissions:
  contents: write
  deployments: write
jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          node-version: 21
          cache: "npm"
      - name: Clean install
        run: npm ci
      - name: Run number[][] benchmark
        run: npm run bench:number | tee benchmark_results/number.txt
      - name: Store number[][] results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: number[][] Benchmark
          tool: "benchmarkjs"
          output-file-path: benchmark_results/number.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "150%"
          comment-on-alert: true
          fail-on-alert: true
      - name: Run bigint[][] benchmark
        run: npm run bench:bigint | tee benchmark_results/bigint.txt
      - name: Store bigint[][] results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: bigint[][] Benchmark
          tool: "benchmarkjs"
          output-file-path: benchmark_results/bigint.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "150%"
          comment-on-alert: true
          fail-on-alert: true
