name: Benchmark
on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
  deployments: write
jobs:
  benchmark:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          node-version: 21
          cache: "npm"
      - name: Clean install
        run: npm ci
      - name: Create results directory
        run: mkdir -p benchmark_results
      - name: Run benchmarks
        run: npm run bench:ci | tee benchmark_results/ci.txt
      - name: Store results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Munkres Benchmarks
          tool: "benchmarkjs"
          output-file-path: benchmark_results/ci.txt
          github-token: ${{ secrets.BENCHMARK_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: "150%"
          comment-on-alert: true
          fail-on-alert: true
